export const FETCH_STATUSES = "FETCH_STATUSES";
export const FETCH_STATUS = "FETCH_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const CREATE_STATUS = "CREATE_STATUS";

export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const CREATE_USER = "CREATE_USER";
export const FETCH_USER = "FETCH_USER";

export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const NO_MESSAGE = "NO_MESSAGE";

export const FETCH_ADS = "FETCH_ADS";
export const DELETE_AD = "DELETE_AD";
export const UPDATE_AD = "UPDATE_AD";
export const FETCH_AD = "FETCH_AD";
export const CREATE_AD = "CREATE_AD";

export const FETCH_NEWSLETTER_EMAILS = "FETCH_NEWSLETTER_EMAILS";
export const REMOVE_FROM_NEWSLETTER = "REMOVE_FROM_NEWSLETTER";
export const ADD_TO_NEWSLETTER = "ADD_TO_NEWSLETTER";
export const UPDATE_EMAIL_IN_NEWSLETTER = "UPDATE_EMAIL_IN_NEWSLETTER";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const FETCH_ARTICLE = "FETCH_ARTICLE";

export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER = "FETCH_ORDER";

export const FETCH_USER_STATISTICS = "FETCH_USER_STATISTICS";
export const FETCH_TRANSACTION_STATISTICS = "FETCH_TRANSACTION_STATISTICS";

export const FETCH_INFO = "FETCH_INFO";
export const UPDATE_INFO = "UPDATE_INFO";
